-- Insert 4 intent registration drafts for paulyn@example.com
INSERT INTO intent_registration_drafts (
  user_id, entity_id, activity_level, activity_description, preparatory_work_description,
  commencement_date, completion_date, draft_name, project_site_address, district, province, llg,
  total_area_sqkm, project_site_description, site_ownership_details, government_agreement,
  departments_approached, approvals_required, landowner_negotiation_status, estimated_cost_kina,
  prescribed_activity_id, latitude, longitude
) VALUES 
-- Draft 1: Level 2 - Lae, Morobe Province - Oil and Gas Drilling
(
  '17d50d9a-b5a2-4d03-b563-bd694ace1467',
  '26e28469-6419-4a3f-ad03-5f7c5cb53753',
  'Level 2A',
  'Exploratory oil and gas drilling operations in the Markham Valley region to assess potential petroleum reserves. The project involves drilling 3 exploration wells to depths of approximately 2,500 meters.',
  'Site clearing and access road construction, establishment of drilling pad, installation of temporary camp facilities, environmental baseline surveys, and community consultation meetings.',
  '2025-03-01',
  '2026-06-30',
  'Markham Valley Oil Exploration',
  'Lot 45, Markham Road, Lae Industrial Area',
  'Lae',
  'Morobe',
  'Lae Urban',
  2.5,
  'The site is located in the Markham Valley, approximately 15km from Lae city center. The terrain is relatively flat with some undulating areas. Access is via the Highlands Highway.',
  'State lease land with mining exploration license EPL-2024-089',
  'Memorandum of Agreement with Mineral Resources Authority signed',
  'Department of Petroleum and Energy, CEPA, Provincial Administration',
  'Environmental Permit, Petroleum Prospecting License, Land Use Agreement',
  'Completed - MOA signed with 5 landowner groups',
  45000000,
  '52d91592-17d0-498c-af9d-02915b22942c',
  -6.7284,
  147.0035
),
-- Draft 2: Level 2 - Lae, Morobe Province - Sewage Treatment
(
  '17d50d9a-b5a2-4d03-b563-bd694ace1467',
  '26e28469-6419-4a3f-ad03-5f7c5cb53753',
  'Level 2B',
  'Construction and operation of a modern sewage treatment plant to serve the growing population of Lae City. The facility will have capacity to treat wastewater for 25,000 people equivalent.',
  'Geotechnical investigations, detailed engineering design, procurement of treatment equipment, construction of access infrastructure, and public awareness campaigns.',
  '2025-04-15',
  '2027-12-31',
  'Lae City Sewage Treatment Plant',
  'Section 78, Allotment 12, Bumbu, Lae',
  'Lae',
  'Morobe',
  'Lae Urban',
  1.8,
  'Coastal site near the Bumbu River outlet, suitable for treated effluent discharge. The area is zoned for industrial/utility use with minimal residential proximity.',
  'Freehold land purchased from Morobe Provincial Government',
  'Partnership agreement with Lae City Authority for operations',
  'Water PNG, Lae City Authority, Department of Works, CEPA',
  'Environmental Permit, Building Permit, Water Discharge License',
  'In progress - 3 of 4 landowner groups agreed',
  28500000,
  'a3d3147d-d793-48fa-bd60-ee069f394717',
  -6.7320,
  147.0156
),
-- Draft 3: Level 3 - Enga Province - Large Investment Activity
(
  '17d50d9a-b5a2-4d03-b563-bd694ace1467',
  '26e28469-6419-4a3f-ad03-5f7c5cb53753',
  'Level 3',
  'Major gold processing and refinery facility with capital investment exceeding K100 million. The facility will process ore from multiple mining sites in the Enga region with capacity of 500,000 tonnes per year.',
  'Environmental and social impact assessment, community benefit sharing agreement negotiations, detailed engineering feasibility study, baseline environmental monitoring, cultural heritage assessment.',
  '2025-06-01',
  '2029-12-31',
  'Enga Gold Processing Facility',
  'Mining Lease ML-156, Porgera Valley, Enga Province',
  'Porgera-Paiela',
  'Enga',
  'Porgera',
  15.0,
  'High altitude site (2,200m elevation) in the Porgera Valley. The terrain is mountainous with significant vegetation. The site is adjacent to existing mining infrastructure.',
  'Mining Lease granted by Mineral Resources Authority, sublease from Barrick Niugini Ltd',
  'Special Mining Lease Agreement with National Government',
  'Mineral Resources Authority, CEPA, Enga Provincial Government, Department of Treasury',
  'Level 3 Environmental Permit, Mining Permit, Special Business License, Tax Credit Scheme Approval',
  'Ongoing - Complex negotiations with 12 landowner clans',
  125000000,
  '170fd995-32f4-4d17-be5a-9406c4eca6a9',
  -5.4833,
  143.1167
),
-- Draft 4: Level 3 - Port Moresby, NCD - Hazardous Contaminants
(
  '17d50d9a-b5a2-4d03-b563-bd694ace1467',
  '26e28469-6419-4a3f-ad03-5f7c5cb53753',
  'Level 3',
  'Establishment of a chemical manufacturing plant for industrial cleaning products and agricultural chemicals. The facility will handle and process hazardous materials including chlorine compounds and phosphates.',
  'Hazardous materials handling protocols development, emergency response planning, community health risk assessment, air quality baseline monitoring, worker safety training programs.',
  '2025-08-01',
  '2028-06-30',
  'NCD Chemical Manufacturing Plant',
  'Lot 234, Badili Industrial Zone, Port Moresby',
  'Moresby South',
  'National Capital District',
  'Moresby South',
  3.2,
  'Industrial zone site with existing utility connections. Located 2km from residential areas with prevailing winds directing emissions away from populated areas.',
  'Industrial lease from NCDC, previously used as storage facility',
  'Investment Promotion Authority certification obtained',
  'CEPA, Investment Promotion Authority, NCDC, Department of Commerce and Industry',
  'Level 3 Environmental Permit, Hazardous Materials License, Industrial Operating Permit, Import License for Chemicals',
  'Completed - Single customary landowner group, compensation paid',
  78000000,
  '379cbb78-34bd-4fbe-bd99-1f54e5cc9b70',
  -9.4647,
  147.1925
);