
-- Create 4 realistic intent registrations for pmcoy@example.com's entities

-- 1. Island Fisheries PNG Ltd - Level 2 Marina Construction (Milne Bay Province)
INSERT INTO intent_registrations (
  id,
  user_id,
  entity_id,
  prescribed_activity_id,
  activity_level,
  activity_description,
  preparatory_work_description,
  province,
  district,
  llg,
  project_site_address,
  project_site_description,
  latitude,
  longitude,
  total_area_sqkm,
  project_boundary,
  commencement_date,
  completion_date,
  estimated_cost_kina,
  site_ownership_details,
  landowner_negotiation_status,
  government_agreement,
  departments_approached,
  approvals_required,
  status,
  created_at,
  updated_at
) VALUES (
  gen_random_uuid(),
  'ae6a3b27-4bca-42a2-bf3e-94848ed0a4d0',
  '50350dc0-7cdd-45f7-8f4d-733b0b692fa7',
  '895f28b9-49ba-4444-9620-8a6361bb0332', -- Marina construction Level 2
  'Level 2',
  'Construction and operation of a 75-berth commercial fishing marina with fuel dispensing facilities, cold storage warehouses, and vessel maintenance workshop at Alotau Harbor. The marina will service commercial fishing vessels up to 25 meters in length operating in the Coral Sea and Solomon Sea fishing grounds.',
  'Completed preliminary marine surveys, bathymetric mapping, and sediment analysis. Environmental baseline studies ongoing including coral reef assessment and water quality monitoring. Engaged local diving contractors for underwater inspections. Commissioned hydrodynamic modeling study.',
  'Milne Bay',
  'Alotau',
  'Suau Rural',
  'Alotau Harbor Foreshore, Section 42 Allotment 15, Alotau Town',
  'Coastal site located on the eastern side of Alotau Harbor, adjacent to existing wharf infrastructure. Area features mixed coral and sandy substrate with moderate tidal variation of 1.2m. Site includes 180m of waterfront access with existing concrete seawall requiring extension.',
  -10.3167,
  150.4500,
  0.00028,
  '{"type":"Feature","geometry":{"type":"Polygon","coordinates":[[[150.44985,-10.31655],[150.45015,-10.31655],[150.45015,-10.31685],[150.44985,-10.31685],[150.44985,-10.31655]]]},"properties":{"name":"Alotau Marina Development","area_hectares":2.8}}',
  '2025-06-01',
  '2027-12-31',
  18500000,
  'State Lease 42/15 held by Milne Bay Provincial Government. Sub-lease agreement in negotiation with PNG Ports Corporation. Traditional fishing rights acknowledged with Suau clan representatives.',
  'Advanced negotiations with Suau Clan Committee. MOU signed December 2024 covering benefit sharing and local employment quotas. Awaiting final endorsement from Alotau LLG.',
  'Letter of support received from Milne Bay Provincial Administration. National Fisheries Authority endorsement pending.',
  'National Fisheries Authority, PNG Ports Corporation, Milne Bay Provincial Administration, National Maritime Safety Authority',
  'Environmental Permit (CEPA), Maritime Safety Certification, Provincial Development Consent, Fisheries License',
  'pending',
  NOW() - INTERVAL '5 days',
  NOW() - INTERVAL '5 days'
);

-- 2. Highlands Agriculture Co. - Level 2 Waste Treatment (Eastern Highlands Province)  
INSERT INTO intent_registrations (
  id,
  user_id,
  entity_id,
  prescribed_activity_id,
  activity_level,
  activity_description,
  preparatory_work_description,
  province,
  district,
  llg,
  project_site_address,
  project_site_description,
  latitude,
  longitude,
  total_area_sqkm,
  project_boundary,
  commencement_date,
  completion_date,
  estimated_cost_kina,
  site_ownership_details,
  landowner_negotiation_status,
  government_agreement,
  departments_approached,
  approvals_required,
  status,
  created_at,
  updated_at
) VALUES (
  gen_random_uuid(),
  'ae6a3b27-4bca-42a2-bf3e-94848ed0a4d0',
  'd36267cc-8942-42f4-a72a-32ded44f1c2e',
  '84046c76-34f8-4ef2-bc45-780da4351dbb', -- Waste treatment Level 2
  'Level 2',
  'Establishment of an integrated organic waste processing facility to convert coffee pulp, banana stems, and vegetable waste from the Goroka agricultural processing zone into commercial-grade compost and biogas. Annual processing capacity of 15,000 tonnes of organic material with biogas generation for on-site power.',
  'Completed feasibility study with Asian Development Bank technical assistance. Soil permeability tests conducted at proposed site. Baseline air quality and groundwater monitoring stations installed. Engaged German composting technology consultants for system design.',
  'Eastern Highlands',
  'Goroka',
  'Asaro-Watabung Rural',
  'Kama Agricultural Station, 8km south of Goroka on Okuk Highway',
  'Gently sloping grassland site at 1,580m elevation within existing agricultural research station. Well-drained volcanic soils, access to permanent creek for process water. Buffer zone of 500m from nearest residential area. Existing power connection and sealed road access.',
  -6.1250,
  145.3833,
  0.00025,
  '{"type":"Feature","geometry":{"type":"Polygon","coordinates":[[[145.38265,-6.12475],[145.38395,-6.12475],[145.38395,-6.12545],[145.38265,-6.12545],[145.38265,-6.12475]]]},"properties":{"name":"Goroka Organic Processing Facility","area_hectares":2.5}}',
  '2025-04-15',
  '2026-10-31',
  8750000,
  'Portion 284 registered to Department of Agriculture & Livestock. Long-term lease agreement executed with NARI (National Agricultural Research Institute). Land classified as agricultural/industrial.',
  'Site within government land. Consultations completed with Asaro-Watabung LLG and adjacent landowner clans. Community benefit agreement includes local employment and free compost allocation to smallholder farmers.',
  'Project identified in Eastern Highlands Provincial Development Plan 2023-2027. Co-funding commitment from Climate Change Development Authority under Green Growth Initiative.',
  'Department of Agriculture & Livestock, NARI, Eastern Highlands Provincial Administration, Climate Change Development Authority',
  'Environmental Permit (CEPA), Provincial Development Consent, DAL Site Approval, Building Permit',
  'pending',
  NOW() - INTERVAL '12 days',
  NOW() - INTERVAL '12 days'
);

-- 3. Sepik River Transport Ltd - Level 3 Major Infrastructure (East Sepik Province)
INSERT INTO intent_registrations (
  id,
  user_id,
  entity_id,
  prescribed_activity_id,
  activity_level,
  activity_description,
  preparatory_work_description,
  province,
  district,
  llg,
  project_site_address,
  project_site_description,
  latitude,
  longitude,
  total_area_sqkm,
  project_boundary,
  commencement_date,
  completion_date,
  estimated_cost_kina,
  site_ownership_details,
  landowner_negotiation_status,
  government_agreement,
  departments_approached,
  approvals_required,
  status,
  created_at,
  updated_at
) VALUES (
  gen_random_uuid(),
  'ae6a3b27-4bca-42a2-bf3e-94848ed0a4d0',
  '41b32dd8-57ae-4b4a-ac11-d53dfddfabdb',
  '170fd995-32f4-4d17-be5a-9406c4eca6a9', -- Level 3 Major investment >K50M
  'Level 3',
  'Development of an integrated river transport hub at Angoram including a modern cargo wharf with 500-tonne crane capacity, passenger terminal, fuel depot with 2 million litre storage, vessel maintenance yard, and cold chain facility. Project includes dredging of 3.5km approach channel to maintain 4m draft access during dry season.',
  'Completed river hydrological study covering 10-year flow data. Commissioned EIS scoping study with AECOM International. Secured commitment from World Bank IFC for project financing assessment. Geotechnical investigations of riverbank stability completed. Cultural heritage survey of impact area underway.',
  'East Sepik',
  'Angoram',
  'Angoram Urban',
  'Angoram Station Riverfront, adjacent to Provincial Works Depot',
  'Strategic location at confluence of Sepik River and Keram tributary. Site comprises 2.9 hectares of reclaimed riverbank with existing basic wharf structure. Water depth 6-12m depending on season. High sediment load requires ongoing maintenance dredging. Site includes heritage-listed colonial-era warehouse.',
  -4.0667,
  144.0667,
  0.00029,
  '{"type":"Feature","geometry":{"type":"Polygon","coordinates":[[[144.06555,-4.06605],[144.06745,-4.06605],[144.06745,-4.06755],[144.06555,-4.06755],[144.06555,-4.06605]]]},"properties":{"name":"Angoram River Transport Hub","area_hectares":2.9}}',
  '2025-09-01',
  '2029-06-30',
  78500000,
  'Portion 47 Angoram held as State Lease by East Sepik Provincial Government. Foreshore and riverbed areas under National Government jurisdiction. Heritage building listed under National Cultural Property Act requires preservation integration.',
  'Extensive consultations with 12 clans along affected river section. Sepik River Traditional Owners Alliance formed as negotiating body. Draft benefit sharing agreement includes revenue share, employment targets, and cultural protection measures. Public notice period completed.',
  'Project designated as National Priority Infrastructure under Medium Term Development Plan IV. Memorandum of Understanding with Department of Transport covering operational standards. East Sepik Provincial Executive Council resolution of support.',
  'Department of Transport, Department of Works, National Cultural Commission, East Sepik Provincial Administration, PNG Waterways Authority, National Maritime Safety Authority',
  'Environmental Permit Level 3 (CEPA), Development Consent, Transport License, Heritage Impact Approval, Dredging Permit, Fuel Storage License',
  'pending',
  NOW() - INTERVAL '18 days',
  NOW() - INTERVAL '18 days'
);

-- 4. Pacific Mining Corporation - Level 3 Mining Activities (Morobe Province)
INSERT INTO intent_registrations (
  id,
  user_id,
  entity_id,
  prescribed_activity_id,
  activity_level,
  activity_description,
  preparatory_work_description,
  province,
  district,
  llg,
  project_site_address,
  project_site_description,
  latitude,
  longitude,
  total_area_sqkm,
  project_boundary,
  commencement_date,
  completion_date,
  estimated_cost_kina,
  site_ownership_details,
  landowner_negotiation_status,
  government_agreement,
  departments_approached,
  approvals_required,
  status,
  created_at,
  updated_at
) VALUES (
  gen_random_uuid(),
  'ae6a3b27-4bca-42a2-bf3e-94848ed0a4d0',
  '51e5c902-1ac9-4b7f-a6c0-45e770aba1ef',
  'f704d414-10e5-4d70-92a2-1382526381a1', -- Level 3 Special Mining Lease
  'Level 3',
  'Development of the Wau-Bulolo Gold Project involving rehabilitation and expansion of historical mining area. Project includes establishment of carbon-in-leach gold processing plant with 500,000 tonne annual ore capacity, tailings storage facility with geomembrane liner, and associated infrastructure. Estimated gold recovery of 45,000 ounces annually over 12-year mine life.',
  'Completed JORC-compliant resource estimation confirming 1.2 million ounce gold deposit. Metallurgical test work at ALS laboratories completed. Draft EIS prepared by SRK Consulting. Hydrological baseline study and acid rock drainage assessment finalized. Archaeological survey of historical mining heritage completed.',
  'Morobe',
  'Wau-Bulolo',
  'Watut Rural',
  'Edie Creek Mining Lease Area, 15km southeast of Wau Township',
  'Mountainous terrain at 1,200-1,800m elevation within historical goldfield. Site includes rehabilitated areas from colonial-era dredging operations. Dense rainforest cover on undisturbed portions. Multiple permanent streams requiring diversion or protection. Access via sealed road from Lae (180km).',
  -7.3500,
  146.7333,
  0.00027,
  '{"type":"Feature","geometry":{"type":"Polygon","coordinates":[[[146.73215,-7.34925],[146.73445,-7.34925],[146.73445,-7.35075],[146.73215,-7.35075],[146.73215,-7.34925]]]},"properties":{"name":"Wau-Bulolo Gold Project Processing Area","area_hectares":2.7}}',
  '2025-12-01',
  '2037-12-31',
  245000000,
  'Application lodged for Special Mining Lease over Exploration License 2847. Processing facility site on Portion 892 under registered lease from Morobe Provincial Government. Tailings facility requires additional land acquisition from customary owners.',
  'Mining Development Forum established with 8 affected landowner groups. Framework agreement executed covering royalty sharing, local procurement, and community development fund. Relocation and compensation negotiations ongoing for 23 households.',
  'Project endorsed by Mining Advisory Council. State Negotiating Team appointed by Minister for Mining. Draft Mining Development Contract under negotiation covering fiscal terms, local content, and environmental bonds.',
  'Mineral Resources Authority, Department of Mining, Morobe Provincial Administration, Department of Environment and Conservation, Internal Revenue Commission, Bank of Papua New Guinea',
  'Environmental Permit Level 3 (CEPA), Special Mining Lease (MRA), Mining Development Contract, Water Use Permit, Waste Management License, Radiation Safety License',
  'pending',
  NOW() - INTERVAL '25 days',
  NOW() - INTERVAL '25 days'
);
